import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Home from "../src/components/Home";

export default function home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}
